version: '3.8'

services:
  accounts:
    build: ./services/accounts
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - db

  user:
    build: ./services/user
    ports:
      - "5002:5000"
    env_file:
      - .env
    depends_on:
      - db

  transaction:
    build: ./services/transaction
    ports:
      - "5003:5000"
    env_file:
      - .env
    depends_on:
      - db

  payment:
    build: ./services/payment
    ports:
      - "5004:5000"
    env_file:
      - .env
    depends_on:
      - db

  notification:
    build: ./services/notification
    ports:
      - "5005:5000"
    env_file:
      - .env

  gateway:
    build: ./services/gateway
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - accounts
      - user
      - transaction
      - payment
      - notification

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
