global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'accounts'
    static_configs:
      - targets: ['accounts-service:8080']

  - job_name: 'payments'
    static_configs:
      - targets: ['payments-service:8080']

  - job_name: 'users'
    static_configs:
      - targets: ['users-service:8080']

  - job_name: 'transactions'
    static_configs:
      - targets: ['transactions-service:8080']

  - job_name: 'notifications'
    static_configs:
      - targets: ['notifications-service:8080']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway-service:8080']